[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"

# Services configuration will be handled via Railway dashboard 