[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "palpite-f1-backend"

[services.variables]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080" 