services:
  # Frontend Next.js
  - type: web
    name: palpite-f1-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: palpite-f1-backend
          property: host
    
  # Backend Spring Boot (se você tiver)
  - type: web
    name: palpite-f1-backend
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: palpite-f1-db
          property: connectionString
      - key: PORT
        value: 8080

  # Banco PostgreSQL
databases:
  - name: palpite-f1-db
    databaseName: palpitef1
    user: postgres 